### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Werner1201** [Werner1201/EstacionamentoDoPy#1]
- [x] <strike> 1- Na Classe Pátio o ideal para enumerar e limitar o número de carro é uma estrutura de lista do tipo vetórica para "identificar onde cada Veículo está e limitar a entrada de novos caso o Pátio esteja cheio.</strike>
- [x] <strike> 2- Avaliar quais funções precisam de um arquivo de interface próprio e quais apenas precisam ser inclusas na interface principal. </strike> *(Alguns arquivos ainda serão repensados)

### Pátio ToDo
- [ ]  3- Fazer algoritmo para encontrar corretamente o carro pela placa.
- [ ]  4- Fazer as "querys" para encontrar em qual vaga está determinada placa
- [ ] 5- implementar método para armazenar os indexes vagos para inserir novos veículos ou criar critério para sempre inserir onde está vazio e se não existir vazio dize que o pátio está cheio.

### Entrada ToDo
- [ ] 6- Retornar a vaga com as tarefas acima concluídas será possível.

**Comment by Werner1201** [comment]
Primeira Tarefa Já Cumprida

**Comment by Werner1201** [comment]
Segunda tarefa considero cumprida com alguns asteriscos.
