### ISSUE TITLE
TODO #3 Armazenando em Arquivos  e (Future) MySQL connection.

### ISSUE THREAD

**Issue by Werner1201** [Werner1201/EstacionamentoDoPy#3]
### Atualmente:
- [ ] Criar armazenagem com Arquivos JSON (Procurar Módulos Online com métodos Prontos)
Caso não encontre os Módulos
- [ ] Criar um módulo com funções para Manipular o JSON

### Futuramente:
- [ ] Criar estrutura interna do Banco 
- [ ] Adcionar conexão com o Banco de Dados
- [ ] Conseguir realizar entrada e saída de Dados e limitar pelo número de Vagas no pátio.
